# Form implementation generated from reading ui file 'playerDetailsWidget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem

from rules import determine_points


class PlayerDetailsWidget(QtWidgets.QWidget):
    def __init__(self, game, parent=None):
        super(PlayerDetailsWidget, self).__init__(parent)
        self.game = game
        self.game.update_results()
        self.setObjectName("playerDetailsWidget")
        self.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        self.resize(1280, 720)
        self.setMinimumSize(QtCore.QSize(1280, 720))
        self.setMaximumSize(QtCore.QSize(1280, 720))
        self.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Czech, QtCore.QLocale.Country.Czechia))
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listOfPlayers = QtWidgets.QListWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listOfPlayers.sizePolicy().hasHeightForWidth())
        self.listOfPlayers.setSizePolicy(sizePolicy)
        self.listOfPlayers.setObjectName("listOfPlayers")
        self.listOfPlayers.clicked.connect(lambda: self.display_players_statistics())
        self.horizontalLayout.addWidget(self.listOfPlayers)
        self.table = QtWidgets.QTableWidget(self)
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(0)
        self.table.setSortingEnabled(True)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(4, item)
        self.set_column_width()
        self.horizontalLayout.addWidget(self.table)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.back_btn = QtWidgets.QPushButton(self)
        self.back_btn.setObjectName("back_btn")
        self.back_btn.clicked.connect(lambda: self.close())
        self.verticalLayout.addWidget(self.back_btn)
        self.display_list_of_players()

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def set_column_width(self):
        self.table.setColumnWidth(0, 172)
        self.table.setColumnWidth(1, 395)
        self.table.setColumnWidth(2, 152)
        self.table.setColumnWidth(3, 152)
        self.table.setColumnWidth(4, 100)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("playerDetailsWidget", "Procházet hráče"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("playerDetailsWidget", "Fáze"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("playerDetailsWidget", "Zápas / Postupující tým"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("playerDetailsWidget", "Můj výsledek"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("playerDetailsWidget", "Výsledek"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("playerDetailsWidget", "Body"))
        self.back_btn.setText(_translate("playerDetailsWidget", "Zpět"))

    def display_list_of_players(self):
        self.listOfPlayers.clear()
        for idx, nickname in enumerate(self.game.database.get_all_players()):
            self.listOfPlayers.insertItem(idx, nickname[0])

    def display_players_statistics(self):
        player = self.listOfPlayers.currentItem()
        self.table.setRowCount(0)
        matches = self.game.database.get_all_match_guesses(str(player.text()))
        for idx, match in enumerate(matches):
            self.table.insertRow(idx)
            self.table.setItem(idx, 0, QTableWidgetItem(match[1]))
            phase = str(match[1])
            if phase == 'Group Stage':
                self.table.setItem(idx, 1, QTableWidgetItem(str(match[2]) + ' : ' + str(match[3])))
                self.table.setItem(idx, 2, QTableWidgetItem(str(match[4]) + ' : ' + str(match[5])))
                res = self.game.database.get_match_result('Group Stage', match[2], match[3])
                self.table.setItem(idx, 3, QTableWidgetItem(str(res[3]) + ' : ' + str(res[4])))
                self.table.setItem(idx, 4, QTableWidgetItem(str(determine_points(match, res))))
            else:
                self.table.setItem(idx, 1, QTableWidgetItem(str(match[2])))
                self.table.setItem(idx, 2, QTableWidgetItem("✓"))
                res = self.game.database.get_match_result_by_phase_and_home_team(phase, match[2])
                if res is None:
                    self.table.setItem(idx, 3, QTableWidgetItem("X"))
                else:
                    self.table.setItem(idx, 3, QTableWidgetItem("✓"))
                self.table.setItem(idx, 4, QTableWidgetItem(str(determine_points(match, res))))

